runtime: nodejs20
env: standard
instance_class: F2  

handlers:
  # Serve all static assets (lowercase + uppercase)
  - url: /(.*\.(css|js|png|jpg|jpeg|gif|svg|ico|json|webp|woff|woff2|ttf|map|PNG|JPG|JPEG|GIF|SVG|ICO|JSON|WEBP|WOFF|WOFF2|TTF|MAP))$
    static_files: build/\1
    upload: build/.*\.(css|js|png|jpg|jpeg|gif|svg|ico|json|webp|woff|woff2|ttf|map|PNG|JPG|JPEG|GIF|SVG|ICO|JSON|WEBP|WOFF|WOFF2|TTF|MAP)

  # Catch all routes (React Router fallback)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
